### ISSUE TITLE
website not responsive

### ISSUE THREAD

**Issue by Laphatize** [upend/upend.github.io#3]
if your gonna rebel, do it right

**Comment by vassudanagunta** [comment]
It's on GitHub Pages*, which is backed by Cloudflare, so I'm not sure how I could do it more right in terms of reliability. GitHub selling us out not withstanding, they did GitHub pages right. 

Am I missing something in your point? 



\* not for much longer, as UpEnd and I will evacuate as soon as I decide on a new home.

**Comment by vassudanagunta** [comment]
Oh, you mean responsive *design*. Gotcha. I don't know what that has to with being a rebel. I think a real rebel would just go with classic Richard Stallman no style plain text websites.

But if you're so up on this, feel free to submit a pull request, I have more important things to do re "the rebellion".
